import { type AssetInput, ItemNode } from '@pascal-app/core'
export const CATALOG_ITEMS: AssetInput[] = [
  {
    id: 'tesla',
    category: 'outdoor',
    tags: ['floor', 'garage'],
    name: 'Tesla',
    thumbnail: '/buildx/items/tesla/thumbnail.webp',
    src: '/buildx/items/tesla/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.7, 5],
  },
  {
    id: 'ev-wall-charger',
    category: 'appliance',
    tags: ['wall', 'garage'],
    name: 'Ev-wall-charger',
    thumbnail: '/buildx/items/ev-wall-charger/thumbnail.webp',
    src: '/buildx/items/ev-wall-charger/model.glb',
    scale: [1, 1, 1],
    offset: [-0.07, 0.4, 0.15],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.8, 0.5],
    attachTo: 'wall',
  },
  {
    id: 'pillar',
    category: 'outdoor',
    tags: ['structure', 'fencing'],
    name: 'Pillar',
    thumbnail: '/buildx/items/pillar/thumbnail.webp',
    src: '/buildx/items/pillar/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1.3, 0.5],
  },

  {
    id: 'high-fence',
    category: 'outdoor',
    tags: ['fencing'],
    name: 'High Fence',
    thumbnail: '/buildx/items/high-fence/thumbnail.webp',
    src: '/buildx/items/high-fence/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.01, 0],
    rotation: [0, 0, 0],
    dimensions: [4, 4.1, 0.5],
  },

  {
    id: 'medium-fence',
    category: 'outdoor',
    tags: ['fencing'],
    name: 'Medium Fence',
    thumbnail: '/buildx/items/medium-fence/thumbnail.webp',
    src: '/buildx/items/medium-fence/model.glb',
    scale: [0.49, 0.49, 0.49],
    offset: [0, 0.01, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 2, 0.5],
  },

  {
    id: 'low-fence',
    category: 'outdoor',
    tags: ['fencing'],
    name: 'Low Fence',
    thumbnail: '/buildx/items/low-fence/thumbnail.webp',
    src: '/buildx/items/low-fence/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.01, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.8, 0.5],
  },

  {
    id: 'bush',
    category: 'outdoor',
    tags: ['vegetation'],
    name: 'Bush',
    thumbnail: '/buildx/items/bush/thumbnail.webp',
    src: '/buildx/items/bush/model.glb',
    scale: [0.96, 0.96, 0.96],
    offset: [-0.14, 0.01, -0.13],
    rotation: [0, 0, 0],
    dimensions: [3, 1.1, 1],
  },

  {
    id: 'fir-tree',
    category: 'outdoor',
    tags: ['vegetation'],
    name: 'Fir',
    thumbnail: '/buildx/items/fir-tree/thumbnail.webp',
    src: '/buildx/items/fir-tree/model.glb',
    scale: [1, 1, 1],
    offset: [-0.01, 0.05, -0.07],
    rotation: [0, 0, 0],
    dimensions: [0.5, 3, 0.5],
  },

  {
    id: 'tree',
    category: 'outdoor',
    tags: ['vegetation'],
    name: 'Tree',
    thumbnail: '/buildx/items/tree/thumbnail.webp',
    src: '/buildx/items/tree/model.glb',
    scale: [0.65, 0.65, 0.65],
    offset: [-0.02, 0.17, -0.04],
    rotation: [0, 0, 0],
    dimensions: [1, 5, 1],
  },

  {
    id: 'palm',
    category: 'outdoor',
    tags: ['vegetation'],
    name: 'Palm',
    thumbnail: '/buildx/items/palm/thumbnail.webp',
    src: '/buildx/items/palm/model.glb',
    scale: [0.37, 0.37, 0.37],
    offset: [0, 0, 0.02],
    rotation: [0, 0, 0],
    dimensions: [1, 4.5, 1],
  },

  {
    id: 'patio-umbrella',
    category: 'outdoor',
    tags: ['leisure', 'floor'],
    name: 'Patio Umbrella',
    thumbnail: '/buildx/items/patio-umbrella/thumbnail.webp',
    src: '/buildx/items/patio-umbrella/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 3.7, 0.5],
  },

  {
    id: 'sunbed',
    category: 'outdoor',
    tags: ['leisure', 'seating', 'floor'],
    name: 'Sunbed',
    thumbnail: '/buildx/items/sunbed/thumbnail.webp',
    src: '/buildx/items/sunbed/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.04, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1.2, 1.5],
  },

  {
    id: 'window-double',
    category: 'window',
    tags: ['wall'],
    name: 'Double Window',
    thumbnail: '/buildx/items/window-double/thumbnail.webp',
    src: '/buildx/items/window-double/model.glb',
    scale: [0.81, 0.81, 0.81],
    offset: [0, -0.32, 0],
    rotation: [0, 3.14, 0],
    dimensions: [1.5, 1.5, 0.5],
    attachTo: 'wall',
  },

  {
    id: 'window-simple',
    category: 'window',
    tags: ['wall'],
    name: 'Simple Window',
    thumbnail: '/buildx/items/window-simple/thumbnail.webp',
    src: '/buildx/items/window-simple/model.glb',
    scale: [1, 1, 1],
    offset: [1.06, -0.21, 0.05],
    rotation: [0, 3.14, 0],
    dimensions: [1.5, 2, 0.5],
    attachTo: 'wall',
  },

  {
    id: 'window-rectangle',
    category: 'window',
    tags: ['wall'],
    name: 'Rectangle Window',
    thumbnail: '/buildx/items/window-rectangle/thumbnail.webp',
    src: '/buildx/items/window-rectangle/model.glb',
    scale: [0.81, 0.81, 0.81],
    offset: [-1.41, -0.28, 0.08],
    rotation: [0, 3.14, 0],
    dimensions: [2.5, 1.5, 0.5],
    attachTo: 'wall',
  },

  {
    id: 'door-bar',
    category: 'door',
    tags: ['wall'],
    name: 'Door with bar',
    thumbnail: '/buildx/items/door-bar/thumbnail.webp',
    src: '/buildx/items/door-bar/model.glb',
    scale: [1, 1, 1],
    offset: [-0.48, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 2.5, 0.5],
    attachTo: 'wall',
  },

  {
    id: 'glass-door',
    category: 'door',
    tags: ['wall'],
    name: 'Glass Door',
    thumbnail: '/buildx/items/glass-door/thumbnail.webp',
    src: '/buildx/items/glass-door/model.glb',
    scale: [0.9, 0.9, 0.9],
    offset: [-0.52, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 2.5, 0.4],
    attachTo: 'wall',
  },

  {
    id: 'door',
    category: 'door',
    tags: ['wall'],
    name: 'Door',
    thumbnail: '/buildx/items/door/thumbnail.webp',
    src: '/buildx/items/door/model.glb',
    scale: [0.79, 0.79, 0.79],
    offset: [-0.43, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 2, 0.4],
    attachTo: 'wall',
  },

  {
    id: 'parking-spot',
    category: 'outdoor',
    tags: ['leisure', 'floor'],
    name: 'Parking Spot',
    thumbnail: '/buildx/items/parking-spot/thumbnail.webp',
    src: '/buildx/items/parking-spot/model.glb',
    scale: [0.9, 1, 0.78],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    dimensions: [5, 1, 2.5],
  },

  {
    id: 'outdoor-playhouse',
    category: 'outdoor',
    tags: ['leisure', 'kids', 'floor'],
    name: 'Outdoor Playhouse',
    thumbnail: '/buildx/items/outdoor-playhouse/thumbnail.webp',
    src: '/buildx/items/outdoor-playhouse/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 1],
  },

  {
    id: 'skate',
    category: 'outdoor',
    tags: ['leisure', 'kids', 'floor'],
    name: 'Skate',
    thumbnail: '/buildx/items/skate/thumbnail.webp',
    src: '/buildx/items/skate/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.2, 0.5],
  },

  {
    id: 'scooter',
    category: 'outdoor',
    tags: ['leisure', 'kids', 'floor'],
    name: 'Scooter',
    thumbnail: '/buildx/items/scooter/thumbnail.webp',
    src: '/buildx/items/scooter/model.glb',
    scale: [1, 1, 1],
    offset: [0.11, 0, 0.17],
    rotation: [0, 0, 0],
    dimensions: [1, 0.9, 0.5],
  },

  {
    id: 'basket-hoop',
    category: 'outdoor',
    tags: ['leisure', 'sports', 'floor'],
    name: 'Basket Hoop',
    thumbnail: '/buildx/items/basket-hoop/thumbnail.webp',
    src: '/buildx/items/basket-hoop/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1.8, 1],
  },

  {
    id: 'ball',
    category: 'outdoor',
    tags: ['leisure', 'sports', 'floor'],
    name: 'Ball',
    thumbnail: '/buildx/items/ball/thumbnail.webp',
    src: '/buildx/items/ball/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.12, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'wine-bottle',
    category: 'kitchen',
    tags: ['countertop', 'decor'],
    name: 'Wine Bottle',
    thumbnail: '/buildx/items/wine-bottle/thumbnail.webp',
    src: '/buildx/items/wine-bottle/model.glb',
    scale: [1, 1, 1],
    offset: [-0.05, 0, 0.01],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.4, 0.5],
  },

  {
    id: 'fruits',
    category: 'kitchen',
    tags: ['countertop', 'decor'],
    name: 'Fruits',
    thumbnail: '/buildx/items/fruits/thumbnail.webp',
    src: '/buildx/items/fruits/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'cutting-board',
    category: 'kitchen',
    tags: ['countertop'],
    name: 'Cutting Board',
    thumbnail: '/buildx/items/cutting-board/thumbnail.webp',
    src: '/buildx/items/cutting-board/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.1, 0.5],
  },

  {
    id: 'frying-pan',
    category: 'kitchen',
    tags: ['countertop'],
    name: 'Frying Pan',
    thumbnail: '/buildx/items/frying-pan/thumbnail.webp',
    src: '/buildx/items/frying-pan/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.1, 1],
  },

  {
    id: 'kitchen-utensils',
    category: 'kitchen',
    tags: ['countertop'],
    name: 'Kitchen Utensils',
    thumbnail: '/buildx/items/kitchen-utensils/thumbnail.webp',
    src: '/buildx/items/kitchen-utensils/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
  },

  {
    id: 'microwave',
    category: 'kitchen',
    tags: ['countertop', 'electronics'],
    name: 'Microwave',
    thumbnail: '/buildx/items/microwave/thumbnail.webp',
    src: '/buildx/items/microwave/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.03],
    rotation: [0, 0, 0],
    dimensions: [1, 0.3, 0.5],
  },

  {
    id: 'stove',
    category: 'kitchen',
    tags: ['floor', 'large'],
    name: 'Stove',
    thumbnail: '/buildx/items/stove/thumbnail.webp',
    src: '/buildx/items/stove/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.05],
    rotation: [0, 0, 0],
    dimensions: [1, 1, 1],
  },

  {
    id: 'fridge',
    category: 'kitchen',
    tags: ['floor', 'large'],
    name: 'Fridge',
    thumbnail: '/buildx/items/fridge/thumbnail.webp',
    src: '/buildx/items/fridge/model.glb',
    scale: [1, 1, 1],
    offset: [0.01, 0, -0.05],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
  },

  {
    id: 'hood',
    category: 'kitchen',
    tags: ['wall'],
    name: 'Hood',
    thumbnail: '/buildx/items/hood/thumbnail.webp',
    src: '/buildx/items/hood/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.52, 0.01],
    rotation: [0, 0, 0],
    dimensions: [1.5, 1, 1.1],
    attachTo: 'wall-side',
  },

  {
    id: 'kitchen-shelf',
    category: 'kitchen',
    tags: ['wall', 'storage'],
    name: 'Kitchen Shelf',
    thumbnail: '/buildx/items/kitchen-shelf/thumbnail.webp',
    src: '/buildx/items/kitchen-shelf/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.52, 0.01],
    rotation: [0, 0, 0],
    dimensions: [2.5, 1, 1.1],
    attachTo: 'wall-side',
  },

  {
    id: 'kitchen-counter',
    category: 'kitchen',
    tags: ['floor', 'large', 'storage'],
    name: 'Kitchen Counter',
    thumbnail: '/buildx/items/kitchen-counter/thumbnail.webp',
    src: '/buildx/items/kitchen-counter/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.8, 1],
    surface: {
      height: 0.75,
    },
  },

  {
    id: 'kitchen-cabinet',
    category: 'kitchen',
    tags: ['floor', 'large', 'storage'],
    name: 'Kitchen Cabinet',
    thumbnail: '/buildx/items/kitchen-cabinet/thumbnail.webp',
    src: '/buildx/items/kitchen-cabinet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.1, 1],
    surface: {
      height: 1.1,
    },
  },

  {
    id: 'kitchen',
    category: 'kitchen',
    tags: ['floor', 'large'],
    name: 'Kitchen',
    thumbnail: '/buildx/items/kitchen/thumbnail.webp',
    src: '/buildx/items/kitchen/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2.5, 1.1, 1],
  },

  {
    id: 'toilet-paper',
    category: 'bathroom',
    tags: ['wall', 'decor'],
    name: 'Toilet Paper',
    thumbnail: '/buildx/items/toilet-paper/thumbnail.webp',
    src: '/buildx/items/toilet-paper/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.19, 0.12],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
    attachTo: 'wall-side',
  },

  {
    id: 'shower-rug',
    category: 'bathroom',
    tags: ['floor', 'decor'],
    name: 'Shower Rug',
    thumbnail: '/buildx/items/shower-rug/thumbnail.webp',
    src: '/buildx/items/shower-rug/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.1, 0.5],
  },

  {
    id: 'laundry-bag',
    category: 'bathroom',
    tags: ['floor'],
    name: 'Laundry Bag',
    thumbnail: '/buildx/items/laundry-bag/thumbnail.webp',
    src: '/buildx/items/laundry-bag/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.8, 0.5],
  },

  {
    id: 'drying-rack',
    category: 'bathroom',
    tags: ['floor'],
    name: 'Drying Rack',
    thumbnail: '/buildx/items/drying-rack/thumbnail.webp',
    src: '/buildx/items/drying-rack/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.1, 1],
  },

  {
    id: 'washing-machine',
    category: 'bathroom',
    tags: ['floor', 'large', 'electronics'],
    name: 'Washing Machine',
    thumbnail: '/buildx/items/washing-machine/thumbnail.webp',
    src: '/buildx/items/washing-machine/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1, 1],
  },

  {
    id: 'toilet',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Toilet',
    thumbnail: '/buildx/items/toilet/thumbnail.webp',
    src: '/buildx/items/toilet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.23],
    rotation: [0, 0, 0],
    dimensions: [1, 0.9, 1],
  },

  {
    id: 'shower-square',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Squared Shower',
    thumbnail: '/buildx/items/shower-square/thumbnail.webp',
    src: '/buildx/items/shower-square/model.glb',
    scale: [1, 1, 1],
    offset: [0.41, 0, -0.42],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
  },

  {
    id: 'shower-angle',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Angle Shower',
    thumbnail: '/buildx/items/shower-angle/thumbnail.webp',
    src: '/buildx/items/shower-angle/model.glb',
    scale: [1, 1, 1],
    offset: [0.41, 0, -0.42],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 1],
  },

  {
    id: 'bathtub',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Bathtub',
    thumbnail: '/buildx/items/bathtub/thumbnail.webp',
    src: '/buildx/items/bathtub/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    dimensions: [2.5, 0.8, 1.5],
  },

  {
    id: 'bathroom-sink',
    category: 'bathroom',
    tags: ['floor', 'large'],
    name: 'Bathroom Sink',
    thumbnail: '/buildx/items/bathroom-sink/thumbnail.webp',
    src: '/buildx/items/bathroom-sink/model.glb',
    scale: [1, 1, 1],
    offset: [0.11, 0, 0.02],
    rotation: [0, 0, 0],
    dimensions: [2, 1, 1.5],
  },

  {
    id: 'ceiling-fan',
    category: 'appliance',
    tags: ['ceiling', 'climate'],
    name: 'Ceiling fan',
    thumbnail: '/buildx/items/ceiling-fan/thumbnail.webp',
    src: '/buildx/items/ceiling-fan/model.glb',
    scale: [1, 1, 1],
    offset: [-0.12, 0.49, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.5, 1.5],
    attachTo: 'ceiling',
    interactive: {
      effects: [
        {
          kind: 'animation',
          clips: {
            on: 'On',
          },
        },
      ],
      controls: [
        {
          kind: 'toggle',
        },
      ],
    },
  },

  {
    id: 'electric-panel',
    category: 'appliance',
    tags: ['wall', 'electrical'],
    name: 'Electric Panel',
    thumbnail: '/buildx/items/electric-panel/thumbnail.webp',
    src: '/buildx/items/electric-panel/model.glb',
    scale: [0.61, 0.74, 0.7],
    offset: [0, 0, 0.06],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1, 0.3],
    attachTo: 'wall-side',
  },

  {
    id: 'sprinkler',
    category: 'appliance',
    tags: ['ceiling', 'safety'],
    name: 'Sprinkler',
    thumbnail: '/buildx/items/sprinkler/thumbnail.webp',
    src: '/buildx/items/sprinkler/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.45, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
    attachTo: 'ceiling',
  },

  {
    id: 'smoke-detector',
    category: 'appliance',
    tags: ['ceiling', 'safety'],
    name: 'Smoke Detector',
    thumbnail: '/buildx/items/smoke-detector/thumbnail.webp',
    src: '/buildx/items/smoke-detector/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.49, 0],
    rotation: [Math.PI, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
    attachTo: 'ceiling',
  },

  {
    id: 'fire-detector',
    category: 'appliance',
    tags: ['wall', 'safety'],
    name: 'Fire Detector',
    thumbnail: '/buildx/items/fire-detector/thumbnail.webp',
    src: '/buildx/items/fire-detector/model.glb',
    scale: [0.9, 1.4, 0.7],
    offset: [0.02, 0.05, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.3],
    attachTo: 'wall',
  },

  {
    id: 'exit-sign',
    category: 'appliance',
    tags: ['wall', 'safety'],
    name: 'Exit Sign',
    thumbnail: '/buildx/items/exit-sign/thumbnail.webp',
    src: '/buildx/items/exit-sign/model.glb',
    scale: [0.6, 0.5, 0.7],
    offset: [0, 0.04, 0.05],
    rotation: [0, 0, 0],
    dimensions: [1, 0.5, 0.3],
    attachTo: 'wall-side',
  },

  {
    id: 'hydrant',
    category: 'appliance',
    tags: ['floor', 'safety'],
    name: 'Hydrant',
    thumbnail: '/buildx/items/hydrant/thumbnail.webp',
    src: '/buildx/items/hydrant/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.9, 1],
  },

  {
    id: 'alarm-keypad',
    category: 'appliance',
    tags: ['wall', 'safety', 'electrical'],
    name: 'Alarm Keypad',
    thumbnail: '/buildx/items/alarm-keypad/thumbnail.webp',
    src: '/buildx/items/alarm-keypad/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.1, 0.5],
  },

  {
    id: 'thermostat',
    category: 'appliance',
    tags: ['wall', 'climate', 'electrical'],
    name: 'Thermostat',
    thumbnail: '/buildx/items/thermostat/thumbnail.webp',
    src: '/buildx/items/thermostat/model.glb',
    scale: [2.08, 2.1, 2.59],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.1],
    attachTo: 'wall-side',
  },

  {
    id: 'air-conditioning',
    category: 'appliance',
    tags: ['wall', 'climate'],
    name: 'Air Conditioning',
    thumbnail: '/buildx/items/air-conditioning/thumbnail.webp',
    src: '/buildx/items/air-conditioning/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.37, 0.21],
    rotation: [0, 0, 0],
    dimensions: [2, 1, 0.9],
    attachTo: 'wall-side',
  },

  {
    id: 'ac-block',
    category: 'appliance',
    tags: ['floor', 'climate'],
    name: 'AC block',
    thumbnail: '/buildx/items/ac-block/thumbnail.webp',
    src: '/buildx/items/ac-block/model.glb',
    scale: [0.79, 0.79, 0.79],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.1, 1, 1.1],
  },

  {
    id: 'toaster',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Toaster',
    thumbnail: '/buildx/items/toaster/thumbnail.webp',
    src: '/buildx/items/toaster/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'sewing-machine',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Sewing Machine',
    thumbnail: '/buildx/items/sewing-machine/thumbnail.webp',
    src: '/buildx/items/sewing-machine/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.7, 0.5],
  },

  {
    id: 'kettle',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Kettle',
    thumbnail: '/buildx/items/kettle/thumbnail.webp',
    src: '/buildx/items/kettle/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'iron',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Iron',
    thumbnail: '/buildx/items/iron/thumbnail.webp',
    src: '/buildx/items/iron/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'coffee-machine',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Coffee Machine',
    thumbnail: '/buildx/items/coffee-machine/thumbnail.webp',
    src: '/buildx/items/coffee-machine/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.03],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'television',
    category: 'appliance',
    tags: ['floor', 'electronics'],
    name: 'Television',
    thumbnail: '/buildx/items/television/thumbnail.webp',
    src: '/buildx/items/television/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.1, 0.5],
  },

  {
    id: 'computer',
    category: 'appliance',
    tags: ['countertop', 'electronics'],
    name: 'Computer',
    thumbnail: '/buildx/items/computer/thumbnail.webp',
    src: '/buildx/items/computer/model.glb',
    scale: [1, 1, 1],
    offset: [0.01, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 0.5, 0.5],
  },

  {
    id: 'stereo-speaker',
    category: 'appliance',
    tags: ['floor', 'electronics'],
    name: 'Stereo Speaker',
    thumbnail: '/buildx/items/stereo-speaker/thumbnail.webp',
    src: '/buildx/items/stereo-speaker/model.glb',
    scale: [1, 1, 1],
    offset: [0.02, 0, -0.01],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1.1, 0.5],
  },

  {
    id: 'threadmill',
    category: 'furniture',
    tags: ['floor', 'fitness'],
    name: 'Threadmill',
    thumbnail: '/buildx/items/threadmill/thumbnail.webp',
    src: '/buildx/items/threadmill/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2.5, 1.5, 1],
  },

  {
    id: 'barbell-stand',
    category: 'furniture',
    tags: ['floor', 'fitness'],
    name: 'Barbell Stand',
    thumbnail: '/buildx/items/barbell-stand/thumbnail.webp',
    src: '/buildx/items/barbell-stand/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 1.3, 2],
  },

  {
    id: 'barbell',
    category: 'furniture',
    tags: ['floor', 'fitness'],
    name: 'Barbell',
    thumbnail: '/buildx/items/barbell/thumbnail.webp',
    src: '/buildx/items/barbell/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.4, 2],
  },

  {
    id: 'toy',
    category: 'furniture',
    tags: ['floor', 'kids', 'decor'],
    name: 'Toy',
    thumbnail: '/buildx/items/toy/thumbnail.webp',
    src: '/buildx/items/toy/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
  },

  {
    id: 'car-toy',
    category: 'furniture',
    tags: ['floor', 'kids', 'decor'],
    name: 'Car Toy',
    thumbnail: '/buildx/items/car-toy/thumbnail.webp',
    src: '/buildx/items/car-toy/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.4, 1],
  },

  {
    id: 'easel',
    category: 'furniture',
    tags: ['floor', 'decor'],
    name: 'Easel',
    thumbnail: '/buildx/items/easel/thumbnail.webp',
    src: '/buildx/items/easel/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 2.3, 1],
  },

  {
    id: 'pool-table',
    category: 'furniture',
    tags: ['floor', 'leisure'],
    name: 'Pool table',
    thumbnail: '/buildx/items/pool-table/thumbnail.webp',
    src: '/buildx/items/pool-table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2.5, 1, 4],
  },

  {
    id: 'guitar',
    category: 'furniture',
    tags: ['floor', 'decor'],
    name: 'Guitar',
    thumbnail: '/buildx/items/guitar/thumbnail.webp',
    src: '/buildx/items/guitar/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.32, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1.2, 0.5],
  },

  {
    id: 'piano',
    category: 'furniture',
    tags: ['floor', 'decor'],
    name: 'Piano',
    thumbnail: '/buildx/items/piano/thumbnail.webp',
    src: '/buildx/items/piano/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 1.5, 1],
  },

  {
    id: 'round-carpet',
    category: 'furniture',
    tags: ['floor', 'decor'],
    name: 'Round Carpet',
    thumbnail: '/buildx/items/round-carpet/thumbnail.webp',
    src: '/buildx/items/round-carpet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2.5, 0.1, 2.5],
  },

  {
    id: 'rectangular-carpet',
    category: 'furniture',
    tags: ['floor', 'decor'],
    name: 'Rectangular Carpet',
    thumbnail: '/buildx/items/rectangular-carpet/thumbnail.webp',
    src: '/buildx/items/rectangular-carpet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [3, 0.1, 2],
  },

  {
    id: 'cactus',
    category: 'furniture',
    tags: ['floor', 'decor', 'vegetation'],
    name: 'Cactus',
    thumbnail: '/buildx/items/cactus/thumbnail.webp',
    src: '/buildx/items/cactus/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.4, 0.5],
  },

  {
    id: 'small-indoor-plant',
    category: 'furniture',
    tags: ['countertop', 'decor', 'vegetation'],
    name: 'Small Plant',
    thumbnail: '/buildx/items/small-indoor-plant/thumbnail.webp',
    src: '/buildx/items/small-indoor-plant/model.glb',
    scale: [1, 1, 1],
    offset: [-0.01, 0, 0.01],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.7, 0.5],
  },

  {
    id: 'indoor-plant',
    category: 'furniture',
    tags: ['floor', 'decor', 'vegetation'],
    name: 'Indoor Plant',
    thumbnail: '/buildx/items/indoor-plant/thumbnail.webp',
    src: '/buildx/items/indoor-plant/model.glb',
    scale: [1, 1, 1],
    offset: [-0.05, 0, 0.07],
    rotation: [0, 0, 0],
    dimensions: [1, 1.7, 1],
  },

  {
    id: 'ironing-board',
    category: 'furniture',
    tags: ['floor'],
    name: 'Ironing Board',
    thumbnail: '/buildx/items/ironing-board/thumbnail.webp',
    src: '/buildx/items/ironing-board/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 1, 1],
  },

  {
    id: 'coat-rack',
    category: 'furniture',
    tags: ['floor', 'storage'],
    name: 'Coat Rack',
    thumbnail: '/buildx/items/coat-rack/thumbnail.webp',
    src: '/buildx/items/coat-rack/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1.8, 0.5],
  },

  {
    id: 'trash-bin',
    category: 'furniture',
    tags: ['floor'],
    name: 'Trash Bin',
    thumbnail: '/buildx/items/trash-bin/thumbnail.webp',
    src: '/buildx/items/trash-bin/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.6, 0.5],
  },

  {
    id: 'round-mirror',
    category: 'furniture',
    tags: ['wall', 'decor'],
    name: 'Rounded Mirror',
    thumbnail: '/buildx/items/round-mirror/thumbnail.webp',
    src: '/buildx/items/round-mirror/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.32, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1, 0.1],
    attachTo: 'wall-side',
  },

  {
    id: 'picture',
    category: 'furniture',
    tags: ['wall', 'decor'],
    name: 'Picture',
    thumbnail: '/buildx/items/picture/thumbnail.webp',
    src: '/buildx/items/picture/model.glb',
    scale: [1, 1, 1],
    offset: [0.02, 0.45, 0.01],
    rotation: [0, 0, 0],
    dimensions: [2, 1, 0.2],
    attachTo: 'wall-side',
  },

  {
    id: 'books',
    category: 'furniture',
    tags: ['countertop', 'decor'],
    name: 'Books',
    thumbnail: '/buildx/items/books/thumbnail.webp',
    src: '/buildx/items/books/model.glb',
    scale: [1, 1, 1],
    offset: [-0.08, 0, 0.02],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.3, 0.5],
  },

  {
    id: 'column',
    category: 'furniture',
    tags: ['floor', 'structure'],
    name: 'Column',
    thumbnail: '/buildx/items/column/thumbnail.webp',
    src: '/buildx/items/column/model.glb',
    scale: [1, 1, 1],
    offset: [0, 1.26, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 2.6, 0.5],
  },

  {
    id: 'stairs',
    category: 'furniture',
    tags: ['floor', 'structure'],
    name: 'Stairs',
    thumbnail: '/buildx/items/stairs/thumbnail.webp',
    src: '/buildx/items/stairs/model.glb',
    scale: [0.61, 0.61, 0.61],
    offset: [0, 0.03, 1.8],
    rotation: [0, 0, 0],
    dimensions: [1.5, 2.5, 3.5],
  },

  // {
  //   id: "suspended-fireplace",
  //   category: "furniture",
  //   tags: ["ceiling", "decor"],
  //   name: "Suspended Fireplace",
  //   thumbnail: "/items/suspended-fireplace/thumbnail.webp",
  //   src: "/items/suspended-fireplace/model.glb",
  //   scale: [1, 1, 1],
  //   offset: [0, 0.45, 0],
  //   rotation: [0, 0, 0],
  //   dimensions: [0.5, 0.5, 0.5],
  //   attachTo: "ceiling",
  // },

  {
    id: 'tv-stand',
    category: 'furniture',
    tags: ['floor', 'storage'],
    name: 'TV Stand',
    thumbnail: '/buildx/items/tv-stand/thumbnail.webp',
    src: '/buildx/items/tv-stand/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.21, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.4, 0.5],
    surface: {
      height: 0.36,
    },
  },

  {
    id: 'shelf',
    category: 'furniture',
    tags: ['wall', 'storage'],
    name: 'Shelf',
    thumbnail: '/buildx/items/shelf/thumbnail.webp',
    src: '/buildx/items/shelf/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.1, 0.01],
    rotation: [0, 0, 0],
    dimensions: [1, 0.5, 0.7],
    attachTo: 'wall-side',
    surface: {
      height: 0.12,
    },
  },

  {
    id: 'bookshelf',
    category: 'furniture',
    tags: ['floor', 'storage'],
    name: 'Bookshelf',
    thumbnail: '/buildx/items/bookshelf/thumbnail.webp',
    src: '/buildx/items/bookshelf/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 2, 0.5],
  },

  {
    id: 'ceiling-lamp',
    category: 'furniture',
    tags: ['ceiling', 'lighting'],
    name: 'Ceiling Lamp',
    thumbnail: '/buildx/items/ceiling-lamp/thumbnail.webp',
    src: '/buildx/items/ceiling-lamp/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.98, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1, 1],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        {
          kind: 'toggle',
        },
        {
          kind: 'slider',
          label: 'Intensity',
          min: 0,
          max: 100,
          unit: '%',
          displayMode: 'dial',
          default: 100,
        },
      ],
      effects: [
        {
          kind: 'light',
          intensityRange: [0, 2],
          color: '#ffffff',
          offset: [0, -0.5, 0],
        },
      ],
    },
  },
  {
    id: 'recessed-light',
    category: 'furniture',
    tags: ['ceiling', 'lighting'],
    name: 'Recessed Light',
    thumbnail: '/buildx/items/recessed-light/thumbnail.webp',
    src: '/buildx/items/recessed-light/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0.094, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.1, 0.5],
    attachTo: 'ceiling',
    interactive: {
      controls: [
        {
          kind: 'toggle',
        },
        {
          kind: 'slider',
          label: 'Intensity',
          min: 0,
          max: 100,
          unit: '%',
          displayMode: 'dial',
          default: 100,
        },
      ],
      effects: [
        {
          kind: 'light',
          intensityRange: [0, 2],
          color: '#ffffff',
          offset: [0, -0.1, 0],
        },
      ],
    },
  },

  {
    id: 'floor-lamp',
    category: 'furniture',
    tags: ['floor', 'lighting'],
    name: 'Floor Lamp',
    thumbnail: '/buildx/items/floor-lamp/thumbnail.webp',
    src: '/buildx/items/floor-lamp/model.glb',
    scale: [1, 1, 1],
    offset: [0.04, 0, 0.02],
    rotation: [0, 0, 0],
    dimensions: [1, 1.9, 1],
    interactive: {
      controls: [
        {
          kind: 'toggle',
        },
        {
          kind: 'slider',
          label: 'Intensity',
          min: 0,
          max: 100,
          unit: '%',
          displayMode: 'dial',
          default: 100,
        },
      ],
      effects: [
        {
          kind: 'light',
          intensityRange: [0, 2],
          color: '#ffffff',
          offset: [0, 1.4, 0],
        },
      ],
    },
  },

  {
    id: 'table-lamp',
    category: 'furniture',
    tags: ['countertop', 'lighting'],
    name: 'Table Lamp',
    thumbnail: '/buildx/items/table-lamp/thumbnail.webp',
    src: '/buildx/items/table-lamp/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.8, 1],
  },

  {
    id: 'closet',
    category: 'furniture',
    tags: ['floor', 'storage', 'bedroom'],
    name: 'Closet',
    thumbnail: '/buildx/items/closet/thumbnail.webp',
    src: '/buildx/items/closet/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    dimensions: [2, 2.5, 1],
  },

  {
    id: 'dresser',
    category: 'furniture',
    tags: ['floor', 'storage', 'bedroom'],
    name: 'Dresser',
    thumbnail: '/buildx/items/dresser/thumbnail.webp',
    src: '/buildx/items/dresser/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 0.8, 1],
    surface: {
      height: 0.8,
    },
  },

  {
    id: 'bunkbed',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Bunkbed',
    thumbnail: '/buildx/items/bunkbed/thumbnail.webp',
    src: '/buildx/items/bunkbed/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.09],
    rotation: [0, 0, 0],
    dimensions: [2, 1.6, 1.5],
  },

  {
    id: 'double-bed',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Double Bed',
    thumbnail: '/buildx/items/double-bed/thumbnail.webp',
    src: '/buildx/items/double-bed/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.03],
    rotation: [0, 0, 0],
    dimensions: [2, 0.8, 2.5],
  },

  {
    id: 'single-bed',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Single Bed',
    thumbnail: '/buildx/items/single-bed/thumbnail.webp',
    src: '/buildx/items/single-bed/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 0.7, 2.5],
  },

  {
    id: 'sofa',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Sofa',
    thumbnail: '/buildx/items/sofa/thumbnail.webp',
    src: '/buildx/items/sofa/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0.04],
    rotation: [0, 0, 0],
    dimensions: [2.5, 0.8, 1.5],
  },

  {
    id: 'lounge-chair',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Lounge Chair',
    thumbnail: '/buildx/items/lounge-chair/thumbnail.webp',
    src: '/buildx/items/lounge-chair/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0.09],
    rotation: [0, 0, 0],
    dimensions: [1, 1.1, 1.5],
  },

  {
    id: 'stool',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Stool',
    thumbnail: '/buildx/items/stool/thumbnail.webp',
    src: '/buildx/items/stool/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1, 1.2, 1],
  },

  {
    id: 'dining-chair',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Dining Chair',
    thumbnail: '/buildx/items/dining-chair/thumbnail.webp',
    src: '/buildx/items/dining-chair/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [0.5, 1, 0.5],
  },

  {
    id: 'office-chair',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Office Chair',
    thumbnail: '/buildx/items/office-chair/thumbnail.webp',
    src: '/buildx/items/office-chair/model.glb',
    scale: [1, 1, 1],
    offset: [0.01, 0, 0.03],
    rotation: [0, 0, 0],
    dimensions: [1, 1.2, 1],
  },

  {
    id: 'livingroom-chair',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Livingroom Chair',
    thumbnail: '/buildx/items/livingroom-chair/thumbnail.webp',
    src: '/buildx/items/livingroom-chair/model.glb',
    scale: [1, 1, 1],
    offset: [0.01, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [1.5, 0.8, 1.5],
  },

  {
    id: 'bedside-table',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Bedside Table',
    thumbnail: '/buildx/items/bedside-table/thumbnail.webp',
    src: '/buildx/items/bedside-table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    dimensions: [0.5, 0.5, 0.5],
    surface: {
      height: 0.5,
    },
  },

  {
    id: 'coffee-table',
    category: 'furniture',
    tags: ['floor', 'table'],
    name: 'Coffee Table',
    thumbnail: '/buildx/items/coffee-table/thumbnail.webp',
    src: '/buildx/items/coffee-table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.4, 1.5],
    surface: {
      height: 0.3,
    },
  },

  {
    id: 'office-table',
    category: 'furniture',
    tags: ['floor', 'table'],
    name: 'Office Table',
    thumbnail: '/buildx/items/office-table/thumbnail.webp',
    src: '/buildx/items/office-table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    dimensions: [2, 0.8, 1],
    surface: {
      height: 0.75,
    },
  },

  {
    id: 'dining-table',
    category: 'furniture',
    tags: ['floor', 'table'],
    name: 'Dining Table',
    thumbnail: '/buildx/items/dining-table/thumbnail.webp',
    src: '/buildx/items/dining-table/model.glb',
    scale: [1, 1, 1],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    dimensions: [2.5, 0.8, 1],
    surface: {
      height: 0.8,
    },
  },
]
